app/routes/core.py
import math, os
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, flash, current_app, session
from ..extensions import db
from ..models import Posts, Users, Comments
from ..utils import login_required

bp = Blueprint("core", __name__)

@bp.route("/")
def home():
    params = current_app.config.get("PARAMS", {})
    posts = Posts.query.filter_by().all()
    last=math.ceil(len(posts)/int(params['no_of_posts']))
    page=request.args.get('page')
    if(not str(page).isnumeric()):
        page=1
    page=int(page)
    posts=posts[(page-1)*int(params['no_of_posts']):(page-1)*int(params['no_of_posts'])+int(params['no_of_posts'])]
    if (page==1):
        prev="#"
        next="/?page="+str(page+1)
    elif(page==last):
        prev = "/?page=" + str(page - 1)
        next = "#"
    else:
        prev = "/?page=" + str(page - 1)
        next = "/?page=" + str(page + 1)
    return render_template('index.html', params=params, posts=posts, prev=prev, next=next)

@bp.route("/about")
def about():
    params = current_app.config.get("PARAMS", {})
    return render_template('about.html', params=params)


@bp.route("/edit/<string:sno>", methods=['GET', 'POST'])
@login_required
def edit(sno):
    params = current_app.config.get("PARAMS", {})
    uid=session.get('user_id')
    if request.method=='POST':
        box_title=request.form.get('title')
        tline=request.form.get('tline')
        slug=request.form.get('slug')
        content=request.form.get('content')
        date = datetime.now()
        poster_id= uid

        if sno=='0':
            post=Posts(title=box_title,slug=slug,content=content,tagline=tline, date=date, poster_id=poster_id)
            db.session.add(post)
            db.session.commit()
        else:
            post=Posts.query.filter_by(sno=sno).first()
            if not post:
                return "Not found", 404
            if post.poster_id != uid:
                return "Forbidden", 403

            post.title=box_title
            post.slug=slug
            post.content=content
            post.tagline=tline
            post.date=date
            post.poster_id=poster_id
            db.session.commit()
        return redirect('/edit/'+sno)
    post=Posts.query.filter_by(sno=sno).first()
    if post and post.poster_id != session.get('user_id'):
        return "Forbidden", 403
    u = Users.query.get(session.get('user_id'))
    return render_template('edit.html', params=params, post=post, users=u)



@bp.route("/delete/<string:sno>", methods=['GET','POST'])
@login_required
def delete(sno):
    uid=session.get('user_id')
    post=Posts.query.filter_by(sno=sno).first()#we want post not a list of posts
    if not post:
        return "Not found", 404
    if post.poster_id != uid:
        return "Forbidden", 403
    db.session.delete(post)
    db.session.commit()
    return redirect('/dashboard')



@bp.route("/post/<string:post_slug>", methods=['GET'])
def post_route(post_slug):
    params = current_app.config.get("PARAMS", {})
    post = Posts.query.filter_by(slug=post_slug).first()
    comments=Comments.query.filter_by(postpost_id=post.sno)
    user_id = session.get("user_id")
    return render_template('post.html', params=params, post=post , comments=comments, user_id=user_id)

@bp.route("/post/<string:post_slug>/comment", methods=['POST'])
@login_required
def comment(post_slug):
    params = current_app.config.get("PARAMS", {})
    uid=session.get('user_id')
    if not uid:
        return "you are not logged in"
    post = Posts.query.filter_by(slug=post_slug).first()
    comments=request.form.get('comment')
    c=Comments(comment=comments,postpost_id=post.sno,postuser_id=uid)
    db.session.add(c)
    db.session.commit()
    comments = Comments.query.filter_by(postpost_id=post.sno)
    return render_template('post.html', params=params, post=post, comments=comments)

app/templates/_comment_form.html
{# expects: post, user_id in context #}

<div class="card">
  <div class="card-body">
    <h5 class="card-title mb-3">Leave a comment</h5>


      <form action="{{ url_for('core.comment', post_slug=post.slug) }}" method="post">
        <div class="mb-3">
          <textarea name="comment" class="form-control" rows="3" placeholder="Write your comment..." required></textarea>
        </div>
        <button class="btn btn-primary" type="submit">Post Comment</button>
      </form>
    
  </div>
</div>

app/templates/_comment_list.html
{# expects: comments list #}

{% if comments %}
  <ul class="list-group">
    {% for c in comments %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <strong>{{ c.postcu.user_name }}</strong>
          <span class="text-muted small">{{ c.date }}</span>
        </div>
        <div class="mt-1">{{ c.comment }}</div>
      </li>
    {% endfor %}
  </ul>
{% endif %}

app/templates/about.html
{% extends "layout.html" %}
{% block body %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='assets/img/about-bg.jpg') }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{params['about_text']}}</p>
                    </div>
                </div>
            </div>
        </main>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>
{% endblock %}

app/templates/dashboard.html
{% extends "layout.html" %}
{% block body %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='assets/img/home-bg.jpg') }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{users.user_name}} Panel</h1>
                            <span class="subheading">Manage your posts and change them</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}
{% endif %}
{% endwith %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h1>Basic Actions</h1>
                    <a href="/edit/0"><button class="btn btn-primary">Add a new post</button></a>
                    <a href="/logout"><button class="btn btn-primary">Logout</button></a>
                    
                    
                    <!-- Post preview-->
                
<h1>Edit Posts</h1>
<table class="table">
    <thead>
      <tr>
        <th>Sno</th>
        <th>Title</th>
        <th>Date</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
        {% for post in posts %}
      <tr>
        <td>{{post.sno}}</td>
        <td>{{post.title}}</td>
        <td>{{post.date}}</td>
        <td><a href="/edit/{{post.sno}}"><button class="btn btn-primary">Edit</button></a></td>
        <td><a href="/delete/{{post.sno}}"><button class="btn btn-primary">Delete</button></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


                    <!-- Pager-->
                    
                </div>
            </div>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static', filename='js/scripts.js') }}"></script>
    </body>
</html>
{% endblock %}

app/templates/edit.html
{% extends "layout.html" %}
{% block body %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='assets/img/home-bg.jpg') }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{users.user_name}} Panel</h1>
                            <span class="subheading">Manage your posts and change them</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h1>Basic Actions</h1>
                    <a href="/dashboard"><button class="btn btn-primary">Dashboard Home</button></a>
                    <a href="/logout"><button class="btn btn-primary">Logout</button></a>
                    <hr>
                    <!-- Post preview-->
                
<h1>Add/Edit Posts</h1>
<form id="contactForm" action="{{ url_for('core.edit', sno=post.sno) if post else url_for('core.edit', sno=0) }}" method="post" novalidate>
                                <div class="form-floating">
                                    <input class="form-control" id="title" type="text" placeholder="Title" name="title" data-sb-validations="required" value="{{post.title}}" />
                                    <label for="title">Title</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="tline" type="text" placeholder="Tagline" name="tline" data-sb-validations="required,email" value="{{post.tagline}}"/>
                                    <label for="tline">Tagline</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="slug" type="text" placeholder="Slug" name="slug" data-sb-validations="required" value="{{post.slug}}"/>
                                    <label for="phone">Slug</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="content" placeholder="Content" name="content" style="height: 12rem" data-sb-validations="required">{{post.content}}</textarea>
                                    <label for="message">Content</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                            </form>




                    <!-- Pager-->
                    
                </div>
            </div>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static', filename='js/scripts.js') }}"></script>
    </body>
</html>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block body %}

        <!-- Page Header-->
        <header class="masthead mb-0" style="background-image: url('{{url_for('static', filename='assets/img/home-bg.jpg') }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{params['blog_name']}}</h1>
                            <span class="subheading">{{params['tag_line']}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                
                {% for post in posts %}
                    

                    <div class="post-preview">
                        <a href="/post/{{post.slug}}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{post.tagline}}
                            </h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">{{post.poster.user_name}}</a>
                            on {{post.date}}
                        </p>
                    </div>
                    {{post.content[0:143]}}...
                                
                    <!-- Divider-->
                    <hr class="my-4" />
                    </li></a>
                    {% endfor %}


                    <!-- Pager-->
                    <div class="clearfix mb-4">
                        <a class="btn btn-primary float-start px-4 pe-5" href="{{prev}}">← Older Posts</a>
                        <a class="btn btn-primary float-end px-4 ps-5" href="{{next}}" style="padding-left:40px;">Newer Posts →</a>
                        
                    </div>
                </div>
            </div>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static', filename='js/scripts.js') }}"></script>
    </body>
</html>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{{params['blog_name']}}</title>
        <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='assets/favicon.ico') }}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{url_for('static', filename='css/styles.css') }}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">{{params['blog_name']}}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/signup">SignUp</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/login">Login</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/dashboard">Dashboard</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/about">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>

{% block body %} {% endblock %}

        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="{{params['tw_url']}}" target="_blank">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{{params['fb_url']}}" target="_blank">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{{params['gh_url']}}" target="_blank">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; TheCodingThunder 2023</div>
                    </div>
                </div>
            </div>
        </footer>
    

app/templates/login.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Admin Panel</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <style>
      /* Ensure no visual capitalization sneaks in from CSS */
      input[type="password"], input[name="pass"], input[name="userpass"] {
        text-transform: none !important;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{{url_for('static', filename='css/signin.css')}}" rel="stylesheet">
  </head>
  <body class="text-center">

<main class="form-signin">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}
{% endif %}
{% endwith %}
  <form action="/login", method="post">
    {% set fname= 'assets/img/' + params['login_image' ]%}
    <img class="mb-4" src="{{url_for('static', filename=fname)}}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Admin Login</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="uname" name="uname" placeholder="Username" autocomplete="username" autocapitalize="none"autocorrect="off" spellcheck="false" required>
      <label for="uname">Username</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="pass" name="pass" placeholder="Password" autocomplete="current-password" autocapitalize="off" autocorrect="off" spellcheck="false" required>
      <label for="pass">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; {{params['blog_name']}} 2017–2021</p>
  </form>
</main>


    
  </body>
</html>

app/templates/post.html
{% extends "layout.html" %}
{% block body %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename=fname) }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{post.title}}</h1>
                            <h2 class="subheading">{{post.tagline}}</h2>
                            <span class="meta">
                                Posted by
                                <a href="#!">{{post.poster.user_name}}</a>
                                on {{post.date}}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {{post.content}}
                            
                            
                    </div>
                </div>
            </div>
        </article>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
    <!-- Divider-->
                    <hr class="my-4" />
                    </li></a>

                    <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h2>Comments</h2>
                    <hr id="comments">

  {# Always show the form area; if not signed in, show a login prompt #}
  {% include "_comment_form.html" %}

  <hr>

  {# Always show the list of existing comments #}
  {% include "_comment_list.html" %}
</div>
                                
    
    
                            
                        </p>
                    </div>
                </div>
            </div>
                    
                                
                   
</html>

{% endblock %}

app/templates/signup.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Admin Panel</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <style>
      /* prevent any visual capitalization on password fields */
      input[type="password"], input[name="userpass"] { text-transform: none !important; }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{{url_for('static', filename='css/signin.css')}}" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}
{% endif %}
{% endwith %}
  <form action="/signup", method="post" novalidate>
    {% set fname= 'assets/img/' + params['login_image'] %}
    <img class="mb-4" src="{{url_for('static', filename=fname)}}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Admin Sign Up</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="urusername" name="urusername" placeholder="Username" autocomplete="username" autocapitalize="none" autocorrect="off" spellcheck="false" required>
      <label for="urusername">Username</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="userpass" name="userpass" placeholder="Password" autocomplete="new-password" autocapitalize="off" autocorrect="off" spellcheck="false" minlength="8" required>
      <label for="userpass">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; {{params['blog_name']}} 2017–2021</p>
  </form>
</main>


    
  </body>
</html>